# Generated by Django 4.2 on 2023-05-13 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='user',
            new_name='profile',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('film_work', 'profile')},
        ),
    ]
