# Generated by Django 4.2 on 2023-05-13 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_user'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowsingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(auto_now=True)),
                ('film_work', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='browsing_histories', to='app.filmwork')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='browsing_histories', to='accounts.profile')),
            ],
        ),
    ]
