# Generated by Django 4.2 on 2023-05-29 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('app', '0002_rename_user_rating_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browsinghistory',
            name='film_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browsing_histories', to='app.filmwork'),
        ),
        migrations.AlterField(
            model_name='browsinghistory',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browsing_histories', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='filmwork',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='film_works', to='app.currency'),
        ),
    ]
