# Generated by Django 4.2 on 2023-05-28 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('app', '0002_rename_user_rating_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactionType',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='app.filmwork')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('reaction', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='app.reactiontype')),
            ],
            options={
                'unique_together': {('film_work', 'profile')},
            },
        ),
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reactions', to='app.comment')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.reactiontype')),
            ],
            options={
                'unique_together': {('profile', 'comment')},
            },
        ),
    ]
