# Generated by Django 4.2 on 2023-04-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_movie_companies_alter_rating_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.URLField(),
        ),
    ]
