# Generated by Django 4.2 on 2023-05-28 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('app', '0003_reactiontype_reaction_commentreaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reaction',
            new_name='FilmWorkReaction',
        ),
    ]
