# Generated by Django 4.2 on 2023-04-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_person_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='slogan',
            field=models.CharField(null=True),
        ),
    ]
