# Generated by Django 4.2 on 2023-05-30 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_browsinghistory_film_work_and_more'),
        ('app', '0004_rename_reaction_filmworkreaction'),
    ]

    operations = [
    ]
