# Generated by Django 4.2 on 2023-06-01 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_merge_20230530_1241'),
        ('app', '0005_merge_20230530_1920'),
    ]

    operations = [
    ]
