# Generated by Django 4.2 on 2023-05-01 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_rating_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='budget',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.AddField(
            model_name='movie',
            name='currency',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='app.currency'),
            preserve_default=False,
        ),
    ]
