# Generated by Django 4.2 on 2023-05-05 15:21

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(default='profile/default.jpg', upload_to=accounts.models.profile_image_store),
        ),
    ]
