# Generated by Django 4.2 on 2023-05-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_comment_film_work_alter_comment_profile'),
        ('accounts', '0002_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(related_name='profiles', to='app.filmwork'),
        ),
    ]
